on:
  release:
    types:
      - published

permissions: {}

name: release

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false

    - name: Install uv
      uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7.1.1

    - name: Build distributions
      run: uv build

    - name: Upload distributions
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: distributions
        path: dist/

  generate-provenance:
    name: Generate SLSA provenance for distributions
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      id-token: write # To sign the provenance.
      attestations: write # To persist the attestation files.
    steps:
      - name: Download distributions
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: distributions
          path: dist/
      - name: Generate build provenance
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-path: 'dist/*'

  publish:
    name: Publish Python distributions to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pylock-attestations
    needs: [build, generate-provenance]
    permissions:
      # Used to sign the release's artifacts with sigstore-python.
      # Used to publish to PyPI with Trusted Publishing.
      id-token: write
    steps:
      - name: Download distributions
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: distributions
          path: dist/

      - name: Publish distributions
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          attestations: true
